# Generated by Django 2.2.3 on 2019-10-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('estoque', models.IntegerField(blank=True, null=True, verbose_name='Numero')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('obs', models.CharField(max_length=255, verbose_name='Obs')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Chapa',
                'verbose_name_plural': 'Chapas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='* Nome / Empresa')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='* Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='* Fone')),
                ('cnpj', models.CharField(blank=True, max_length=40, null=True, verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, max_length=40, null=True, verbose_name='CPF')),
                ('rua', models.CharField(blank=True, max_length=40, null=True, verbose_name='Rua')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Numero')),
                ('cidade', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=40, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cep')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Serviço')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor_unidade', models.FloatField(blank=True, null=True, verbose_name='Valor Unitario')),
                ('valor_total', models.FloatField(blank=True, null=True, verbose_name='Valor Total')),
                ('entrada', models.FloatField(blank=True, null=True, verbose_name='Valor entrada')),
                ('prazo', models.IntegerField(null=True, verbose_name='Dias para entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('fineshed_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Em adamento'), (1, 'Cancelado'), (2, 'Parado'),
                                                                    (3, 'Pronto'), (4, 'Entregue')], default=0,
                                               verbose_name='Situação')),
                ('chapa',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servico', to='core.Chapa',
                                   verbose_name='Chapa')),
                ('cliente', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT,
                                              related_name='clientes', to='core.Cliente', verbose_name='Cliente')),
            ],
        ),
    ]
