# Generated by Django 2.2.3 on 2019-10-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191018_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='valor_unidade',
        ),
    ]
