# Generated by Django 2.2.3 on 2019-10-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191022_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapa',
            options={'ordering': ['nome'], 'verbose_name': 'Chapa', 'verbose_name_plural': 'Chapas'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Bairro'),
        ),
    ]
