# Generated by Django 2.2.3 on 2020-01-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191114_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
    ]
