# Generated by Django 2.2.3 on 2020-04-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200412_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoclientenota',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Cliente'),
        ),
        migrations.AlterField(
            model_name='grupoclientenota',
            name='nota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Nota'),
        ),
    ]
