# Generated by Django 3.0.6 on 2020-05-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('estoque', models.IntegerField(blank=True, null=True, verbose_name='Quantidade em Estoque')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('obs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Obs')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Chapa',
                'verbose_name_plural': 'Chapas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='* Nome / Empresa')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='* Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='* Fone')),
                ('cnpj', models.CharField(blank=True, max_length=40, null=True, verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, max_length=40, null=True, verbose_name='CPF')),
                ('rua', models.CharField(blank=True, max_length=40, null=True, verbose_name='Rua')),
                ('bairro', models.CharField(blank=True, max_length=40, null=True, verbose_name='Bairro')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Numero')),
                ('cidade', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=40, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cep')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrupoNotaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Saidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('origem', models.IntegerField(blank=True, choices=[(0, 'INVISTA'), (1, 'THE BRINDES')], default=0,
                                               verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Saida',
                'verbose_name_plural': 'Saidas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Serviço')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('chapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servico',
                                            to='core.Chapa', verbose_name='Chapa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes',
                                              to='core.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Servicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.FloatField(default=0, null=True, verbose_name='Desconto')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Em aberto'), (1, 'Pago')], default=0,
                                               verbose_name='Situação')),
                ('servico', models.ManyToManyField(null=True, through='core.GrupoNotaServico', to='core.Servico')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gruponotaservico',
            name='nota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Nota'),
        ),
        migrations.AddField(
            model_name='gruponotaservico',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Servico'),
        ),
        migrations.CreateModel(
            name='GrupoClienteNota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                              to='core.Cliente')),
                ('nota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Nota')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='nota',
            field=models.ManyToManyField(null=True, through='core.GrupoClienteNota', to='core.Nota'),
        ),
    ]
