# Generated by Django 3.0.6 on 2020-05-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizad em')),
                ('origem', models.IntegerField(blank=True, choices=[(0, 'INVISTA'), (1, 'THE BRINDES')], default=0, verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Saida',
                'verbose_name_plural': 'Saidas',
                'ordering': ['-created_at'],
            },
        ),
    ]
