# Generated by Django 2.2.3 on 2019-10-18 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20191018_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes',
                                    to='core.Cliente', verbose_name='Cliente'),
        ),
    ]
