# Generated by Django 2.2.3 on 2019-10-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191018_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='prazo',
        ),
        migrations.AddField(
            model_name='servico',
            name='desconto',
            field=models.FloatField(null=True, verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='fineshed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recibo feito em'),
        ),
    ]
