# Generated by Django 2.2.3 on 2020-01-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200122_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='numero',
        ),
    ]
