# Generated by Django 2.2.3 on 2020-04-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_nota_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['-created_at'], 'verbose_name': 'Servico', 'verbose_name_plural': 'Servicos'},
        ),
        migrations.CreateModel(
            name='GrupoClienteNota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cliente')),
                ('nota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Nota')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='nota',
            field=models.ManyToManyField(null=True, through='core.GrupoClienteNota', to='core.Nota'),
        ),
    ]
