# Generated by Django 2.2.3 on 2020-04-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200411_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruponotaservico',
            name='nota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Nota'),
        ),
        migrations.AlterField(
            model_name='gruponotaservico',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Servico'),
        ),
    ]
