# Generated by Django 4.1.2 on 2022-10-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapa",
            name="valor",
            field=models.FloatField(blank=True, default=None, verbose_name="Valor"),
            preserve_default=False,
        )
    ]
