# Generated by Django 4.1.2 on 2022-10-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_chapa_valor_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="valor_total",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Total"),
        ),
        migrations.AlterField(
            model_name="chapa",
            name="estoque",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Quantidade em Estoque",
            ),
        ),
        migrations.AlterField(
            model_name="chapa",
            name="marca",
            field=models.CharField(
                blank=True, default=None, max_length=50, null=True, verbose_name="Marca"
            ),
        ),
        migrations.AlterField(
            model_name="chapa",
            name="obs",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, verbose_name="Obs"
            ),
        ),
    ]
