name: Python application test with Github Actions

on: [push]

env:
  DEBUG: True
  SECRET_KEY: asdad123123adsa2452
  ALLOWED_HOSTS: localhost, 127.0.0.1
  DATABASE_URL: postgres//postgres:a@localhost:5432/invista
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_STORAGE_BUCKET_NAME:
  INTERNAL_IPS: 127.0.0.1
  SENTRY_DNS: 
  CORS_ORIGIN_WHITELIST: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Format
      run: |
        make format
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        #make test
